// Executive Dashboard, Teilauftrag 1 (Auftrag 070): Kandidaten, die (noch) nicht aktiv sind.
// „aufbereiten“: fachlich geeignet, braucht strukturierte Werte, Fachseite oder Freigabe.
// „nicht_geeignet“ steht in unsuitableEntries.ts.
// Simulations-KPIs sind ausgeschlossen (Plan §1) und stehen deshalb hier nicht.
import type { CatalogSource, DashboardCategory, InventoryCatalogEntry } from '../dashboardCatalog';

const D = (file: string) => `src/domain/${file}.ts`;
const TA8 = 'Teilauftrag 8';

export const entry = (
  id: string,
  name: string,
  category: DashboardCategory,
  source: CatalogSource,
  status: InventoryCatalogEntry['status'],
  reason: string,
  target?: string,
): InventoryCatalogEntry => ({
  id,
  name,
  category,
  kind: id.startsWith('uebersicht.') ? 'uebersicht' : 'kpi',
  source,
  status,
  reason,
  ...(target ? { target } : {}),
});

export const base = (
  file: string,
  exportName: string,
  path?: (string | number)[],
): CatalogSource => ({
  layer: 'baseline',
  module: D(file),
  exportName,
  ...(path ? { path } : {}),
});

/** Fachlich geeignet, aber noch nicht aktiv. */
export const PREPARE_CATALOG_ENTRIES: readonly InventoryCatalogEntry[] = [
  entry(
    'baseline.erloesmix',
    'Erlösmix 2025',
    'finanzen',
    base('finanzenData', 'CHART_ERLOESE', ['datasets', 0, 'data']),
    'aufbereiten',
    'Geeignete Aufteilung: Summe 336.000 € entspricht den Umsatzerlösen 2025. Fachseite s-guv.',
    TA8,
  ),
  entry(
    'baseline.kostenstruktur',
    'Kostenstruktur 2025',
    'finanzen',
    base('finanzenData', 'BUDGET', ['allocations']),
    'aufbereiten',
    'Anteile ergeben 100 %, Beträge 645.000 € entsprechen den GuV-Aufwendungen 2025; Werte nur als Text („490.000 €“). Fachseite s-unit.',
    TA8,
  ),
  entry(
    'baseline.guv',
    'GuV-Positionen',
    'finanzen',
    base('finanzenData', 'GUV', ['rows']),
    'aufbereiten',
    'FY 2024, FY 2025 und Plan 2026 in einer Tabelle; Plan- und Istwerte müssen getrennt gekennzeichnet werden, Werte nur als Text.',
    TA8,
  ),
  entry(
    'baseline.kosten_vergleich',
    'Kosten 2024 und 2025',
    'finanzen',
    base('finanzenData', 'CHART_KOSTEN'),
    'aufbereiten',
    'Vorzeichen uneinheitlich (Kosten positiv, EBITDA negativ, in der GuV alle Kosten negativ); vor der Darstellung normalisieren, negative Werte nie als Kreis.',
    TA8,
  ),
  entry(
    'baseline.unit_economics',
    'Unit Economics',
    'finanzen',
    base('finanzenData', 'UNIT', ['metrics']),
    'aufbereiten',
    'LTV, LTV/CAC, CAC-Payback, Deckungsbeitrag, Bruttomarge, NRR und GRR nur als Text mit Zusätzen („2,7 : 1 (Ziel …)“); strukturierte Einzelwerte nötig. Fachseite s-unit.',
    TA8,
  ),
  entry(
    'baseline.bilanz',
    'Bilanzpositionen',
    'finanzen',
    base('finanzenData', 'BILANZ'),
    'aufbereiten',
    'Stichtagswerte nur als Text-Tabelle ohne Datum im Datensatz; einzelne Posten (z. B. Kassenbestand) erst mit Fachfreigabe. Fachseite s-bilanz.',
    TA8,
  ),
  entry(
    'baseline.arr_nach_segment',
    'ARR nach Segment',
    'kunden',
    base('kundenData', 'CHART_SEGMENT', ['datasets', 0, 'data']),
    'aufbereiten',
    'Geeignete Aufteilung: Summe 411.840 € entspricht dem ARR. Fachseite s-segmente.',
    TA8,
  ),
  entry(
    'baseline.kunden_nach_region',
    'Kunden nach Region',
    'kunden',
    base('kundenData', 'REGIONEN', ['distribution']),
    'aufbereiten',
    'Geeignete Aufteilung: 61 + 3 + 2 = 66 Kunden. Fachseite s-segmente.',
    TA8,
  ),
  entry(
    'baseline.kunden_nach_branche',
    'Kunden nach Branche',
    'kunden',
    base('kundenData', 'SEGMENTE', ['rows']),
    'aufbereiten',
    'Kundenzahlen stehen nur im Text („24 Kunden · …“), die Prozentwerte ergeben 99 %; strukturierte Zählung nötig. Fachseite s-segmente.',
    TA8,
  ),
  entry(
    'baseline.top_kunden',
    'Top-Referenzkunden',
    'kunden',
    base('kundenData', 'TOP10', ['rows']),
    'aufbereiten',
    'Zehn Referenzkunden mit ARR nur als Text; als Übersichtstabelle aufbereiten. Fachseite s-top10.',
    TA8,
  ),
  entry(
    'baseline.customer_success',
    'Customer Success',
    'kunden',
    base('kundenData', 'CS', ['kpis']),
    'aufbereiten',
    'NRR, GRR, Account-Churn, NPS und Time-to-Value nur als Text; die Seite Customer Success ist nicht geroutet, ein Fachseitenziel fehlt.',
  ),
  entry(
    'baseline.funnel_2025',
    'Funnel 2025 je Quartal',
    'vertrieb_crm',
    base('vertriebData', 'FUNNEL', ['chart']),
    'aufbereiten',
    'Leads, MQL, SQL und Neukunden je Quartal 2025, Summen stimmen mit der FY-Spalte überein; Funnel-Stufen, daher nie Kreis. Fachseite s-funnel.',
    TA8,
  ),
  entry(
    'baseline.neukunden_quartal',
    'Neukunden und Vertriebskosten je Quartal',
    'vertrieb_crm',
    base('execData', 'CHART_QUARTAL'),
    'aufbereiten',
    'Zwei Einheiten (Anzahl und T€) in einem Datensatz, auf keiner Fachseite verwendet; Neukunden je Quartal stehen gleichwertig in FUNNEL.',
    TA8,
  ),
  entry(
    'baseline.kanal_mix',
    'Neukunden nach Kanal',
    'marketing',
    base('vertriebData', 'KANAELE', ['chartKanal']),
    'aufbereiten',
    'Anteile je Kanal ergeben 100 % (gerundet aus 47 Neukunden). Fachseite s-kanaele.',
    TA8,
  ),
  entry(
    'baseline.kanal_cac',
    'Marketing-CAC nach Kanal',
    'marketing',
    base('vertriebData', 'KANAELE', ['chartRoi']),
    'aufbereiten',
    'Verhältnis je Kategorie (Spend ÷ Neukunden je Kanal); Darstellung als Kategorienvergleich. Fachseite s-kanaele.',
    TA8,
  ),
  entry(
    'baseline.marketing_budget',
    'Marketingbudget 2025',
    'marketing',
    base('vertriebData', 'MBUDGET', ['chartSpend']),
    'aufbereiten',
    'Budget und Ist-Spend je Kanal; die Seite Marketingbudget ist nicht geroutet, ein Fachseitenziel fehlt.',
  ),
  entry(
    'baseline.reichweite',
    'Digitale Reichweite',
    'marketing',
    base('vertriebData', 'BRAND', ['chart']),
    'aufbereiten',
    'Website-Besucher, LinkedIn-Follower und Newsletter je Quartal in drei Einheiten; die Seite Brand ist nicht geroutet, ein Fachseitenziel fehlt.',
  ),
  entry(
    'baseline.headcount_verlauf',
    'Headcount-Verlauf',
    'organisation',
    base('organisationData', 'HEADCOUNT', ['chart', 'datasets', 0, 'data']),
    'aufbereiten',
    'Geeignete Zeitreihe: FTE je Quartal 2024 bis 2025. Fachseite s-headcount.',
    TA8,
  ),
  entry(
    'baseline.hr_kennzahlen',
    'HR-Kennzahlen',
    'organisation',
    base('organisationData', 'HR', ['metrics']),
    'aufbereiten',
    'Fluktuation, Personalaufwand und Remote-Anteil nur als Text mit Zusätzen; strukturierte Werte nötig. Fachseite s-hr.',
    TA8,
  ),
  entry(
    'baseline.produkt_nutzung',
    'Aktivierung und KI-Scoring-Nutzung',
    'produkt',
    base('produktData', 'CHART_PRODUKT'),
    'aufbereiten',
    'Zwei Prozent-Zeitreihen je Quartal 2025, im Plan für Teilauftrag 8 vorgemerkt. Fachseite s-perf.',
    TA8,
  ),
  entry(
    'baseline.kuendigungsgruende',
    'Kündigungsgründe',
    'produkt',
    base('produktData', 'CHART_CHURN', ['datasets', 0, 'data']),
    'aufbereiten',
    'Aufteilung 8 + 5 + 2 + 2 = 17 Accounts; der Zeitraum der Zählung steht nicht in der Quelle und muss vor der Aufnahme belegt werden. Fachseite s-perf.',
    TA8,
  ),
  entry(
    'baseline.produkt_qualitaet',
    'Produktqualität',
    'produkt',
    base('produktData', 'PERF', ['metrics']),
    'aufbereiten',
    'Uptime, Aktivierung, WAU/MAU und weitere nur als Text mit Zielzusatz; strukturierte Werte nötig. Fachseite s-perf.',
    TA8,
  ),
  entry(
    'baseline.marktanteile',
    'Marktanteile Europa/DACH',
    'markt',
    base('marktData', 'CHART_WETTBEWERB', ['datasets', 0, 'data']),
    'aufbereiten',
    'Anteile ergeben 74,4 % (keine Gesamtheit, daher nie Kreis); LeadPilot „< 0,1 %“ ist als 0,1 gespeichert und damit eine Obergrenze. Fachseite s-wettbewerb.',
    TA8,
  ),
  entry(
    'baseline.gesellschafter',
    'Gesellschafter',
    'recht',
    base('rechtData', 'GESELLSCHAFTER', ['rows']),
    'aufbereiten',
    'Stimmrechtsanteile; die Summenzeile „Gesamt“ wird ausgeschlossen, die fünf Anteile ergeben exakt 100 % (Test). Fachseite s-gesellschafter.',
    TA8,
  ),
  entry(
    'uebersicht.meilensteine',
    'Meilensteine',
    'unternehmen',
    base('unternehmenData', 'HISTORIE', ['events']),
    'aufbereiten',
    'Meilensteinübersicht von der Gründung bis zum GJ 2025; als Übersichtskachel geeignet. Fachseite s-historie.',
    TA8,
  ),
  entry(
    'live.arr_mix',
    'Live-ARR-Mix',
    'live',
    {
      layer: 'live',
      module: 'src/services/liveKpi/liveKpiDefinitions.ts',
      exportName: 'LIVE_KPI_DEFINITIONS',
    },
    'aufbereiten',
    'Aufteilung aus vier Live-Werten; ein gemeinsamer bestätigter Snapshot ist nicht belegt (Plan §4, Kombinationen). Die Einzelwerte sind aktiv.',
  ),
  entry(
    'live.funnel',
    'Live-Funnel',
    'live',
    {
      layer: 'live',
      module: 'src/services/liveKpi/liveKpiDefinitions.ts',
      exportName: 'LIVE_KPI_DEFINITIONS',
    },
    'aufbereiten',
    'Funnel aus fünf Live-Werten; derselbe Snapshot ist nicht belegt; Funnel-Stufen nie Kreis. Die Einzelwerte sind aktiv.',
  ),
  entry(
    'live.verlauf',
    'Live-Verlauf',
    'live',
    {
      layer: 'live',
      module: 'src/services/liveKpi/liveKpiStreamHistory.ts',
      exportName: 'mergeIntoHistory',
    },
    'aufbereiten',
    'Sitzungshistorie seit Seitenaufruf ist keine vollständige Zeitreihe (Plan §4); Verlaufsdarstellung erst mit Teilauftrag 2.',
  ),
];
