// Executive Dashboard, Teilauftrag 1 (Auftrag 070): Kandidaten mit Status „nicht_geeignet“.
// Plan-, Ziel- oder Schätzwerte, Fließtext oder technische Register, jeweils mit Grund.
import type { InventoryCatalogEntry } from '../dashboardCatalog';
import { base, entry } from './inventoryEntries';

const PLAN =
  'Planwerte, keine Istwerte; eine Plan/Ist-Trennung ist im ersten Katalogumfang nicht vorgesehen.';
const TEXT = 'Fließtext oder Stammdaten ohne Messwert; Text ist keine Datenquelle (Plan §8).';

export const UNSUITABLE_CATALOG_ENTRIES: readonly InventoryCatalogEntry[] = [
  entry(
    'baseline.branchen_anteile',
    'Branchenanteile',
    'kunden',
    base('execData', 'CHART_TIER'),
    'nicht_geeignet',
    'Anteile 36 + 27 + 21 + 15 = 99 % ergeben keine Gesamtheit, auf keiner Seite verwendet; Ersatz ist baseline.kunden_nach_branche.',
  ),
  entry(
    'baseline.mrr_plan',
    'MRR-Plan 2026',
    'finanzen',
    base('finanzenData', 'CHART_MRR26'),
    'nicht_geeignet',
    PLAN,
  ),
  entry(
    'baseline.churn_plan',
    'Churn- und Trial-Plan 2026',
    'finanzen',
    base('finanzenData', 'CHART_CHURN26'),
    'nicht_geeignet',
    PLAN,
  ),
  entry(
    'baseline.budget_plan',
    'Budget 2026',
    'finanzen',
    base('finanzenData', 'CHART_BUDGET'),
    'nicht_geeignet',
    PLAN,
  ),
  entry(
    'baseline.marketingplanung',
    'Marketingplanung H2 2026',
    'marketing',
    base('vertriebData', 'PLANUNG'),
    'nicht_geeignet',
    'Monatsbudgets und Ziele sind Planwerte; die Zielgrafik mischt skalierte Einheiten („€/10“).',
  ),
  entry(
    'baseline.kampagne',
    'Kampagne LeadPilot Connect',
    'marketing',
    base('vertriebData', 'KAMPAGNE'),
    'nicht_geeignet',
    'Planung einer Einzelkampagne ohne Zeitraum- und Istnachweis; die Seite ist nicht geroutet.',
  ),
  entry(
    'baseline.okr_vergleich',
    'OKR Basis und Ziel',
    'strategie',
    base('strategieData', 'CHART_OKR'),
    'nicht_geeignet',
    'Basis- und Zielwerte in skalierten Mischeinheiten („T€/10“, „x10“); Ziele sind keine Istwerte.',
  ),
  entry(
    'baseline.wachstumstreiber',
    'Wachstumstreiber',
    'strategie',
    base('strategieData', 'CHART_TREIBER'),
    'nicht_geeignet',
    'Geschätzte ARR-Effekte auf Annahmen, keine gemessenen Werte.',
  ),
  entry(
    'baseline.burn_runway',
    'Burn Rate und Runway',
    'finanzen',
    base('execData', 'NOTE_HIGHLIGHTS'),
    'nicht_geeignet',
    'Burn Rate 25.750 € je Monat und Runway 14 Monate stehen nur im Fließtext (Highlights, SWOT, OKR); ' +
      TEXT,
  ),
  entry(
    'baseline.trial_conversion',
    'Trial-to-Paid',
    'vertrieb_crm',
    base('execData', 'HIGHLIGHTS_BAD_ROWS'),
    'nicht_geeignet',
    'Trial-to-Paid 18 % nur im Fließtext und als Basis in Planungsgrafiken; keine strukturierte Istquelle.',
  ),
  entry(
    'baseline.unternehmensprofil',
    'Unternehmensprofil',
    'unternehmen',
    base('execData', 'PROFILE_ROWS'),
    'nicht_geeignet',
    TEXT,
  ),
  entry(
    'baseline.unternehmen_texte',
    'Idee, Value Proposition, Standort',
    'unternehmen',
    base('unternehmenData', 'IDEE'),
    'nicht_geeignet',
    TEXT,
  ),
  entry(
    'baseline.strategie_texte',
    'OKR, BSC, Maßnahmen, Treiber, Risiken',
    'strategie',
    base('strategieData', 'OKR'),
    'nicht_geeignet',
    TEXT,
  ),
  entry(
    'baseline.markt_texte',
    'Marktlage und SWOT',
    'markt',
    base('marktData', 'MARKT'),
    'nicht_geeignet',
    TEXT,
  ),
  entry(
    'baseline.kunden_texte',
    'ICP, Persona, Empathy Map',
    'kunden',
    base('kundenData', 'ICP'),
    'nicht_geeignet',
    TEXT,
  ),
  entry(
    'baseline.vertrieb_texte',
    'SLA, Content, Tools',
    'vertrieb_crm',
    base('vertriebData', 'SLA'),
    'nicht_geeignet',
    TEXT,
  ),
  entry(
    'baseline.produkt_texte',
    'Funktionen, Preismodell, Architektur',
    'produkt',
    base('produktData', 'PRICING'),
    'nicht_geeignet',
    'Preisliste und Funktionsbeschreibungen sind Stammdaten ohne Messwert; ' + TEXT,
  ),
  entry(
    'baseline.recht_texte',
    'Satzung, Handelsregister, Verträge',
    'recht',
    base('rechtData', 'SATZUNG'),
    'nicht_geeignet',
    TEXT,
  ),
  entry(
    'baseline.geschaeftsmodell',
    'Business Model Canvas',
    'strategie',
    base('geschaeftsmodellData', 'BMC'),
    'nicht_geeignet',
    TEXT,
  ),
  entry(
    'baseline.projektkontext',
    'Projektkontext',
    'unternehmen',
    base('projektkontextData', 'PROJEKT'),
    'nicht_geeignet',
    TEXT,
  ),
  entry(
    'baseline.technische_register',
    'Navigation, Ressourcen, Bildregister',
    'unternehmen',
    base('navData', 'NAV_CATEGORIES'),
    'nicht_geeignet',
    'Technische Register (navData, resourceRegistry, faceliftVisualData) ohne Kennzahlen.',
  ),
];
